---
title: "CODEBOOK"
author: "Wenhao Y"
date: "April 11, 2016"
output: md_document
---
Code Book

This code book will describe the data used in this project, as well as the processing required to create the resulting tidy data set.

Overview

30 volunteers performed 6 different activities while wearing a smartphone. The smartphone captured various data about their movements.

Explanation of each file

features.txt: Names of the 561 features.
activity_labels.txt: Names and IDs for each of the 6 activities.

train.x.txt: 7352 observations of the 561 features, for 21 of the 30 volunteers.

test.subject.txt: A vector of 7352 integers, denoting the ID of the volunteer related to each of the observations in train.x.txt.
train.y.txt: A vector of 7352 integers, denoting the ID of the activity related to each of the observations in train.x.txt.

X_test.txt: 2947 observations of the 561 features, for 9 of the 30 volunteers.

test.subject.txt: A vector of 2947 integers, denoting the ID of the volunteer related to each of the observations in X_test.txt.
y_test.txt: A vector of 2947 integers, denoting the ID of the activity related to each of the observations in X_test.txt.
More information about the files is available in README.txt. More information about the features is available in features_info.txt.